### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by marbar3778**
Closes: #XXX

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Comment by marbar3778** [comment]
i keep getting 
```
# github.com/99designs/keyring
../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:136:8: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:181:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:181:21: undefined: keychain.Access
../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:187:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:187:21: undefined: keychain.Access
make: *** [build] Error 2
```

@alessio can you try on your machine?

**Comment by alessio** [comment]
```
alessio@bangalter:~/work/peggy$ go build ./...
# github.com/cosmos/cosmos-sdk/client/context
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/client/context/context.go:68:15: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/client/context/context.go:160:17: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/client/context/verifier.go:46:17: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
# github.com/cosmos/cosmos-sdk/server
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/server/tm_cmds.go:50:14: assignment mismatch: 1 variable but privValidator.GetPubKey returns 2 values
```

**Comment by marbar3778** [comment]
brought tendermint back down to 0.33.3 you shouldn't have that issue anymore

**Comment by okwme** [comment]
also getting a keyring error:
```
# github.com/99designs/keyring
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:136:8: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:181:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:181:21: undefined: keychain.Access
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:187:9: kcItem.SetAccess undefined (type keychain.Item has no field or method SetAccess)
../../../go/pkg/mod/github.com/99designs/keyring@v1.1.5/keychain.go:187:21: undefined: keychain.Access

```

**Comment by alessio** [comment]
I can't build it yet, dependencies and `go.{mod,sum}` still need fixing:

```
alessio@bangalter:~/work/peggy$ git log --oneline -n 1
9d2031b (HEAD -> marko/bump_deps, origin/marko/bump_deps) bring tendermint tp 0.33.3
alessio@bangalter:~/work/peggy$ make build
go: updates to go.sum needed, disabled by -mod=readonly
Makefile:12: recipe for target 'build' failed
make: *** [build] Error 1
alessio@bangalter:~/work/peggy$ go build ./...
# github.com/cosmos/peggy/cmd/ebrelayer/relayer
cmd/ebrelayer/relayer/ethereum.go:138:79: bridgeBankContractABI.Events["github.com/cosmos/peggy/cmd/ebrelayer/types".LogLock.String()].Id undefined (type abi.Event has no field or method Id, but does have ID)
cmd/ebrelayer/relayer/ethereum.go:143:105: cosmosBridgeContractABI.Events["github.com/cosmos/peggy/cmd/ebrelayer/types".LogNewProphecyClaim.String()].Id undefined (type abi.Event has no field or method Id, but does have ID)
alessio@bangalter:~/work/peggy$ git diff
diff --git a/go.sum b/go.sum
index 8dce7ae..920e734 100644
--- a/go.sum
+++ b/go.sum
@@ -257,6 +257,7 @@ github.com/google/gofuzz v1.0.0/go.mod h1:dBl0BpW6vV/+mYPU4Po3pmUjxk6FQPldtuIdl/
 github.com/google/renameio v0.1.0/go.mod h1:KWCgfxg9yswjAJkECMjeO8J8rahYeXnNhOm40UhjYkI=
 github.com/google/uuid v1.0.0 h1:b4Gk+7WdP/d3HZH8EJsZpvV7EtDOgaZLtnaNGIu1adA=
 github.com/google/uuid v1.0.0/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
+github.com/google/uuid v1.1.1 h1:Gkbcsh/GbpXz7lPftLA3P6TYMwjCLYm83jiFQZF/3gY=
 github.com/google/uuid v1.1.1/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=
 github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1 h1:EGx4pi6eqNxGaHF6qqu48+N2wcFQ5qg5FXgOdqsJ5d8=
 github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1/go.mod h1:wJfORRmW1u3UXTncJ5qlYoELFm8eSnnEO6hX4iZ3EWY=
```

**Comment by marbar3778** [comment]
`go get ./...` usually works for me when im trying to fix this issue: `go: updates to go.sum needed, disabled by -mod=readonly`

must be a linux issue 😉

**Comment by alessio** [comment]
```
alessio@bangalter:~/work/peggy$ go get ./...
# github.com/cosmos/peggy/cmd/ebrelayer/relayer
cmd/ebrelayer/relayer/ethereum.go:138:79: bridgeBankContractABI.Events["github.com/cosmos/peggy/cmd/ebrelayer/types".LogLock.String()].Id undefined (type abi.Event has no field or method Id, but does have ID)
cmd/ebrelayer/relayer/ethereum.go:143:105: cosmosBridgeContractABI.Events["github.com/cosmos/peggy/cmd/ebrelayer/types".LogNewProphecyClaim.String()].Id undefined (type abi.Event has no field or method Id, but does have ID)
```

Wrt `go: updates to go.sum needed, disabled by -mod=readonly`, that is exactly why we use `-mod=readonly`: we want to avoid losing control on our packages dependencies.
`go build` and `go install` attempt to satisfy dependencies automatically by `go get`ting everything a package needs to finally update `go.{mod,sum}` - unless one uses `-mod=readonly`.

**Comment by alessio** [comment]
I'm experiencing a different issue now:

```
alessio@bangalter:~/work/peggy$ make build
# github.com/cosmos/cosmos-sdk/client/context
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/client/context/context.go:68:15: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/client/context/context.go:160:17: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/client/context/verifier.go:46:17: undefined: "github.com/tendermint/tendermint/rpc/client".NewHTTP
# github.com/cosmos/cosmos-sdk/server
../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.3/server/tm_cmds.go:50:14: assignment mismatch: 1 variable but privValidator.GetPubKey returns 2 values
Makefile:12: recipe for target 'build' failed
make: *** [build] Error 2
```

CI fails because of this too.

**Comment by marbar3778** [comment]
Gonna close this as it's outdated now

**Pull request closed without merging**
