### PR TITLE
Update Peggy to latest SDK master

### PR DESCRIPTION
**Pull request by fedekunze**
- [x] use `go mod` instead of `dep`
- [ ] Updates to the latest SDK

### CODE REVIEW

**Comment by marbar3778** [comment]
@fedekunze what you think of merging this as merely the go.mod and update sdk version?

**Comment by fedekunze** [comment]
Sure, we can upgrade this to support NFTs afterwards

**Comment by marbar3778** [comment]
@fedekunze how should we handle the rest, seems the modules need some updating now. should we bring this up for a starting point for swish, or should we try to handle it?

**Comment by fedekunze** [comment]
I'll find some time early next week to update it

**Comment by musnit** [comment]
partially included in Update to SDK 0.37 #65, closing

**Pull request closed without merging**
